version: "3.9"

networks:
  apps:

services:
  auth:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile-auth
    restart: always
    profiles:
      - dev
    ports:
      - "8090:8090"
    networks:
      - apps
    depends_on:
      - db

  mock:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile-mock
    restart: always
    profiles:
      - dev
    ports:
      - "8080:8080"
    networks:
      - apps

  front:
    build: ./frontend/
    restart: always
    profiles:
      - dev
    ports:
      - "3000:3000"
    networks:
      - apps

  db:
    image: postgres:15.0
    restart: always
    profiles:
      - db-only
      - dev
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - apps

  adminer:
    image: adminer
    restart: always
    profiles:
      - db-only
      - dev
    ports:
      - 8081:8080
    networks:
      - apps

  liquibase:
    image: liquibase/liquibase:4.17
    restart: on-failure
    profiles:
      - db-only
      - dev
    networks:
      - apps
    volumes:
      - ./backend/liquibase:/liquibase/changelog/
    command: --changeLogFile=./changelog-master.yml --username=postgres --password=example --url=jdbc:postgresql://db:5432/postgres update
    depends_on:
      - db