version: "3.9"

networks:
  apps:

services:
  auth:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile-auth
    restart: always
    ports:
      - "8090:8090"
    networks:
      - apps
    depends_on:
      - db

  mock:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile-mock
    restart: always
    ports:
      - "8080:8080"
    networks:
      - apps

  front:
    build: ./frontend/
    restart: always
    ports:
      - "3000:3000"
    networks:
      - apps

  db:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - apps

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - apps

  liquibase:
    image: liquibase/liquibase
    restart: always
    networks:
      - apps
    volumes:
      - ./backend/liquibase:/liquibase/changelog/
    command: --defaults-file=liquibase.docker.properties update
    depends_on:
      - db